# Project configuration for Cycle Time Prediction (PySpark ETL + ML)
time_series_columns:
  - E
  - F
  - G
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - O
  - P
id_column: "A"
#id_column: null
cycle_number_column: "B"
timestamp_column: "C"
good_bad_label_column: "D"
csv_path: data/cycles.csv
raw_parquet_path: outputs/raw_spark.parquet
features_parquet_path: outputs/features_spark.parquet
split:
  train: 0.7
  val: 0.15
  test: 0.15
max_gap_sec: 300
